### ISSUE TITLE
Demo-/Live-Instanz?

### ISSUE THREAD

**Issue by pwilimzig** [ECCdigital/smart-city-booking-vue-app#11]
Klingt spannend! Gibt es bereits eine Live-Instanz des Tools?

**Comment by AlexDoell** [comment]
Hi Philipp,

aktuell gibt es eine Demo-Instanz, die hier liegt und folge Login-Daten für den Demo User verwendet:

https://demo1.smart-city-booking.de/
Benutzername: demo@smart-city-booking.de
Passwort: demo
